server:
  db_url: postgres://postgres:postgres@localhost:5432/chat
  port: 8080
  redis_url: rediss://127.0.0.1:6379/
key_pair:
  private_key: |-
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIEtdQHvQo3TEftRrC5Y/XD+Lxnh9qqd4+lAtpfewIqIB
    -----END PRIVATE KEY-----
  public_key: |-
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAaR40m8HMRlE/E2yYXT6fl8s9citeFezUTOVuknqir1c=
    -----END PUBLIC KEY-----
