POST http://localhost:8080/api/sign_up
Content-Type: application/json

{
    "username": "testuser",
  "email" : "123444@qq.com",
    "password": "password123",
  "workspace": "test",
  "ws_id": 1
}

### sign in
POST http://localhost:8080/api/sign_in
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}